### ISSUE TITLE
non-MRI support?

### ISSUE THREAD

**Issue by jf** [nviennot/nobrainer#156]
sorry to have to file an issue to ask; but I thought this might be relevant here as well. nobrainer.io says "NoBrainer runs on Ruby MRI 2.x.". What does this mean exactly? No support for other VMs?

**Comment by nviennot** [comment]
JRuby is supported, I've put in in the continuous integration: https://travis-ci.org/nviennot/nobrainer
However I had to disable a test. This fails on Travis: https://github.com/nviennot/nobrainer/blob/master/spec/integration/types_spec.rb#L317-L335 due to Time.parse / iso8601 differences with MRI.
But passes on my local machine. I didn't investigate further, which is why I didn't put official support for JRuby on the docs.

I have no clue if Rubinius passes.

Does this answer your question?
PS: Feel free to fix the JRuby build on travis :) :)

**Comment by jf** [comment]
Thanks, Nicolas! I'm actually specifically more interested in Rubinius than in JRuby. What would it take to be able to find out?

**Comment by nviennot** [comment]
I can't install Rubinius: `rvm install rbx` ends with :

```
...
Detected old configuration settings, forcing a clean build
  Checking for 'llvm-config': only LLVM 3.0-3.5 is supported
ABORT: unable to set up LLVM
```

For you to find out, simply run the nobrainer test suite:

```ruby
git clone https://github.com/nviennot/nobrainer.git
cd nobrainer
bundle install
rspec
```

**Comment by katafrakt** [comment]
I ran NoBrainer tests with Rubinius 2.5.8 and it passed so it looks pretty good.

**Comment by nviennot** [comment]
Cool! Can you make a PR with an updated .travis.yml configuration file please?

**Comment by katafrakt** [comment]
Done. Build is green: https://travis-ci.org/nviennot/nobrainer/builds/82115807
