### ISSUE TITLE
Model collisions on CamelCase naming.

### ISSUE THREAD

**Issue by shadowbq** [nviennot/nobrainer#181]
SyncSchema on a CamelCase model.

```ruby 
class FooBar
   include NoBrainer::Document
end
```

then add an additional Model with the SubName Foo

```ruby
class Foo
   include NoBrainer::Document
end
```

will cause during `NoBrainer.sync_schema`

``` shell
r.table("nobrainer_locks").get...NoMethodError: undefined method `lock' for nil:NilClass
```

**Comment by shadowbq** [comment]
Nope.. false positive.. so sorry.. just a reserved word due to Namespace inclusions in rethinkdb.

This was a naming collision based on a class document called 'monitor'

This is a collision in rethinkdb-2.2.01/lib/net.rb due to a 'send' call.

**Comment by nviennot** [comment]
So if the model is called `Monitor` that may cause problem due to collisions with the ruby [Monitor](http://ruby-doc.org/stdlib-2.1.2/libdoc/monitor/rdoc/Monitor.html). But if you have a namespaced model like `Foo::Monitor`, you should be okay. So if the latter doesn't work, that's a bug. Let me know :)
