### ISSUE TITLE
Basic Toolbox for Rails Apps

### ISSUE THREAD

**Issue by vanboom** [nviennot/nobrainer#96]
NoBrainer team...  I wanted to drop a suggestion on a list of other gems that need nobrainer support that might help speed adoption.  Mongoid is ahead of us on this path.

1. Kaminari support - for pagination.
2. Ransack support - for easy searching. 
3. Devise support - for user logins...although a relational database might be better suited here.
4. Apartment for multi-tenancy
5. Geocoder
6. more?

Thanks for your work to help enable RethinkDB in the RoR environment!

**Comment by dmitry** [comment]
@eksoverzero any news? I would like to hear about it, because I would like to start a new project with RethinikDB, and still thinking is it worth it or just use plain PostreSQL.

**Comment by eksoverzero** [comment]
@dmitry The project never went live using RethinkDB unfortunately. Due to time constraints. I tried, but ran out of time to try convert some much needed Mongoid gems to work with Nobrainer. Though I do still work on them in an off branch of the project, @nviennot helped me out, in hopes I can switch it over sometime or another.

Sorry.
